import com.mysql.jdbc.ResultSetMetaData;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author JJ Mangampat
 */
public class Allowance extends javax.swing.JFrame {

    /**
     * Creates new form Allowance
     */
    public Allowance() {
        initComponents();
        connection();
        table_data();
        Loadempno();
    }
    
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
    public void connection(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/allowancesystem","root","");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Employee.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Employee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void Loadempno(){
        
        try {
            pst = con.prepareStatement("SELECT empno,department FROM employee");
            rs = pst.executeQuery();   
            txtempno.removeAllItems();
            txtdetype.removeAllItems();
            
            while(rs.next()){
                txtempno.addItem(rs.getString(1));
                txtdetype.addItem(rs.getString(2));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Allowance.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void table_data(){
        
        int q;
        
        try {
            pst = con.prepareStatement("SELECT * FROM allowance");
            rs = pst.executeQuery();
            
            ResultSetMetaData rss = (ResultSetMetaData) rs.getMetaData();
            q = rss.getColumnCount();
            
            DefaultTableModel df = (DefaultTableModel)jTable1.getModel();
            DefaultTableModel df1 = (DefaultTableModel)jTable2.getModel();
            DefaultTableModel df2 = (DefaultTableModel)jTable3.getModel();
            df.setRowCount(0);
            df1.setRowCount(1);
            df2.setRowCount(2);
            
            while(rs.next()){
                
                Vector v2 = new Vector();
                for(int a=1;a<=q;a++){
                    v2.add(rs.getString("id"));
                    v2.add(rs.getString("allowance_type"));
                    v2.add(rs.getString("amount"));
                    v2.add(rs.getString("empno"));
                }
                
                df.addRow(v2);
                 df1.addRow(v2);
                 df2.addRow(v2);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Allowance.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtallo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtamount = new javax.swing.JTextField();
        btnSaveAllow = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtalloInd = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtamountIndi = new javax.swing.JTextField();
        btnSaveInd = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtempno = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtalloDep = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtamountDep = new javax.swing.JTextField();
        btnSaveDep = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtdetype = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        btnCloseAllow = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manage Employee Allowance");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(232, 231, 232));
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane1.setFont(new java.awt.Font("Catamaran SemiBold", 0, 12)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(232, 231, 232));
        jPanel1.setFont(new java.awt.Font("Catamaran Medium", 0, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Catamaran", 0, 12)); // NOI18N
        jLabel1.setText("Allowance Type");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtallo.setFont(new java.awt.Font("Catamaran", 0, 12)); // NOI18N
        txtallo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Accomodation", "Transportation", "Meals", "Benefits" }));
        txtallo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel2.setFont(new java.awt.Font("Catamaran", 0, 12)); // NOI18N
        jLabel2.setText("Amount");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtamount.setFont(new java.awt.Font("Catamaran", 0, 12)); // NOI18N
        txtamount.setText("ex. 5000");
        txtamount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtamountActionPerformed(evt);
            }
        });

        btnSaveAllow.setFont(new java.awt.Font("Catamaran", 0, 12)); // NOI18N
        btnSaveAllow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btsubmit.png"))); // NOI18N
        btnSaveAllow.setBorder(null);
        btnSaveAllow.setBorderPainted(false);
        btnSaveAllow.setContentAreaFilled(false);
        btnSaveAllow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSaveAllow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveAllowActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Catamaran", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "ALLOWANCE", "AMOUNT", "EMPLOYEE NO."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtamount, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtallo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSaveAllow)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(btnSaveAllow))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtallo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtamount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("All Employees", jPanel1);

        jPanel2.setBackground(new java.awt.Color(232, 231, 232));

        jTable2.setFont(new java.awt.Font("Catamaran", 0, 12)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "ALLOWANCE", "AMOUNT", "EMPLOYEE NO."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setViewportView(jTable2);

        jLabel3.setFont(new java.awt.Font("Catamaran", 0, 12)); // NOI18N
        jLabel3.setText("Allowance Type");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtalloInd.setFont(new java.awt.Font("Catamaran", 0, 12)); // NOI18N
        txtalloInd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Accomodation", "Transportation", "Meals", "Benefits" }));
        txtalloInd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel4.setFont(new java.awt.Font("Catamaran", 0, 12)); // NOI18N
        jLabel4.setText("Amount");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtamountIndi.setFont(new java.awt.Font("Catamaran", 0, 12)); // NOI18N
        txtamountIndi.setText("ex. 5000");
        txtamountIndi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtamountIndiActionPerformed(evt);
            }
        });

        btnSaveInd.setBackground(new java.awt.Color(232, 231, 232));
        btnSaveInd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btsubmit.png"))); // NOI18N
        btnSaveInd.setBorder(null);
        btnSaveInd.setBorderPainted(false);
        btnSaveInd.setContentAreaFilled(false);
        btnSaveInd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSaveInd.setOpaque(true);
        btnSaveInd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveIndActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Catamaran", 0, 12)); // NOI18N
        jLabel5.setText("Employee No.");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtempno.setFont(new java.awt.Font("Catamaran", 0, 12)); // NOI18N
        txtempno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        txtempno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtempno, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtamountIndi, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtalloInd, javax.swing.GroupLayout.Alignment.LEADING, 0, 350, Short.MAX_VALUE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSaveInd))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtempno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnSaveInd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(51, 51, 51))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtalloInd, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtamountIndi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(161, 161, 161))
        );

        jTabbedPane1.addTab("Individual", jPanel2);

        jPanel3.setBackground(new java.awt.Color(232, 231, 232));

        jLabel6.setFont(new java.awt.Font("Catamaran", 0, 12)); // NOI18N
        jLabel6.setText("Allowance Type");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtalloDep.setFont(new java.awt.Font("Catamaran", 0, 12)); // NOI18N
        txtalloDep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Accomodation", "Transportation", "Meals", "Benefits" }));
        txtalloDep.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel7.setFont(new java.awt.Font("Catamaran", 0, 12)); // NOI18N
        jLabel7.setText("Amount");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtamountDep.setFont(new java.awt.Font("Catamaran", 0, 12)); // NOI18N
        txtamountDep.setText("ex. 5000");
        txtamountDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtamountDepActionPerformed(evt);
            }
        });

        btnSaveDep.setBackground(new java.awt.Color(232, 231, 232));
        btnSaveDep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btsubmit.png"))); // NOI18N
        btnSaveDep.setBorder(null);
        btnSaveDep.setBorderPainted(false);
        btnSaveDep.setContentAreaFilled(false);
        btnSaveDep.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSaveDep.setOpaque(true);
        btnSaveDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveDepActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Catamaran", 0, 12)); // NOI18N
        jLabel8.setText("Department");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtdetype.setFont(new java.awt.Font("Catamaran", 0, 12)); // NOI18N
        txtdetype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        txtdetype.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jTable3.setFont(new java.awt.Font("Catamaran", 0, 12)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "ALLOWANCE", "AMOUNT", "EMPLOYEE NO."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane3.setViewportView(jTable3);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtdetype, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtamountDep, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtalloDep, javax.swing.GroupLayout.Alignment.LEADING, 0, 350, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(btnSaveDep, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtdetype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtalloDep, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btnSaveDep)
                        .addGap(22, 22, 22)))
                .addComponent(txtamountDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135))
        );

        jTabbedPane1.addTab("Department", jPanel3);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 490, 370));

        jLabel9.setFont(new java.awt.Font("Helvetica Rounded", 0, 30)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(47, 47, 47));
        jLabel9.setText("Manage Employee Allowance");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        btnCloseAllow.setFont(new java.awt.Font("Catamaran", 0, 12)); // NOI18N
        btnCloseAllow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnback.png"))); // NOI18N
        btnCloseAllow.setBorderPainted(false);
        btnCloseAllow.setContentAreaFilled(false);
        btnCloseAllow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCloseAllow.setOpaque(false);
        btnCloseAllow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseAllowActionPerformed(evt);
            }
        });
        getContentPane().add(btnCloseAllow, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 40));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Back");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 18, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg1.jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtamountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtamountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtamountActionPerformed

    private void btnSaveAllowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveAllowActionPerformed
        // TODO add your handling code here:
        
        String allo = txtallo.getSelectedItem().toString();
        String amount = txtamount .getText();
        
        try {
            pst = con.prepareStatement("SELECT empno FROM employee");
            rs = pst.executeQuery();
            
           String empnovalue;
           
           while (rs.next()){
               
               empnovalue = rs.getString("empno"); 
               pst = con.prepareStatement("INSERT INTO allowance(allowance_type, amount, empno)VALUES(?,?,?)");
               pst.setString(1, allo);
               pst.setString(2, amount);
               pst.setString(3, empnovalue);
               
               pst.executeUpdate();
           }
           table_data();
           JOptionPane.showMessageDialog(this,"Allowance successfully added to all employee");
           txtamount.setText("");
           
        } catch (SQLException ex) {
            Logger.getLogger(Allowance.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSaveAllowActionPerformed

    private void btnCloseAllowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseAllowActionPerformed
        // TODO add your handling code here:
        
        new MainForm().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCloseAllowActionPerformed

    private void btnSaveIndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveIndActionPerformed
        // TODO add your handling code here:

        String empno = txtempno.getSelectedItem().toString();
        String allowtype = txtalloInd.getSelectedItem().toString();
        String amount = txtamountIndi.getText();

        try {
            pst = con.prepareStatement("INSERT INTO allowance(allowance_type, amount, empno)VALUES(?,?,?)");
            pst.setString(1, allowtype);
            pst.setString(2, amount);
            pst.setString(3, empno);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Allowance Added!!");
            table_data();
        } catch (SQLException ex) {
            Logger.getLogger(Allowance.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSaveIndActionPerformed

    private void txtamountIndiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtamountIndiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtamountIndiActionPerformed

    private void btnSaveDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveDepActionPerformed
        // TODO add your handling code here:

        String depart = txtdetype.getSelectedItem().toString();
        String allow = txtalloDep.getSelectedItem().toString();
        String amount = txtamountDep.getText();

        try {
            pst = con.prepareStatement("SELECT empno FROM employee WHERE department =?");
            pst.setString(1,depart);
            rs = pst.executeQuery();

            String empvalue;
            while(rs.next()){

                empvalue = rs.getString("empno");
                pst = con.prepareStatement("INSERT INTO allowance(allowance_type,amount,empno)VALUES(?,?,?)");
                pst.setString(1,allow);
                pst.setString(2, amount);
                pst.setString(3, empvalue);
                pst.executeUpdate();
            }

            JOptionPane.showMessageDialog(this,"Successfully added to department");
            txtamount.setText("");
        } catch (SQLException ex) {
            Logger.getLogger(Allowance.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnSaveDepActionPerformed

    private void txtamountDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtamountDepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtamountDepActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Allowance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Allowance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Allowance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Allowance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Allowance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCloseAllow;
    private javax.swing.JButton btnSaveAllow;
    private javax.swing.JButton btnSaveDep;
    private javax.swing.JButton btnSaveInd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JComboBox<String> txtallo;
    private javax.swing.JComboBox<String> txtalloDep;
    private javax.swing.JComboBox<String> txtalloInd;
    private javax.swing.JTextField txtamount;
    private javax.swing.JTextField txtamountDep;
    private javax.swing.JTextField txtamountIndi;
    private javax.swing.JComboBox<String> txtdetype;
    private javax.swing.JComboBox<String> txtempno;
    // End of variables declaration//GEN-END:variables
}
