/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author JJ Mangampat
 */
import java.sql. *;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class Employee extends javax.swing.JFrame {

    /**
     * Creates new form Employee
     */
    public Employee() {
        initComponents();
        connection();
        AutoID();
    }
    
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
    public void connection(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/allowancesystem","root","");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Employee.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Employee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void AutoID(){
        
        try {

            Statement s = con.createStatement();
            try {
                rs = (ResultSet) s.executeQuery("SELECT MAX(empno) FROM employee");
                rs.next();
                rs.getString("MAX(empno)");
                
                if(rs.getString("MAX(empno)")==null){
                    txtno.setText("EM001");
                }else{
                    long id = Long.parseLong(rs.getString("MAX(empno)").substring(2,rs.getString("MAX(empno)").length()));
                    id++;
                    txtno.setText("EM" + String.format("%03d",id));
                }
            } catch (SQLException ex) {
                Logger.getLogger(Employee.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Employee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtno = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtfname = new javax.swing.JTextField();
        txtlname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtaddress = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txttelno = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtsalary = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtdepart = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Employee Registration");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Rounded", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(47, 47, 47));
        jLabel1.setText("Employee Registration");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Catamaran SemiBold", 0, 14)); // NOI18N
        jLabel2.setText("EMPLOYEE NO.:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, -1, -1));

        txtno.setFont(new java.awt.Font("Catamaran", 0, 14)); // NOI18N
        txtno.setText("EM###");
        getContentPane().add(txtno, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Catamaran", 0, 12)); // NOI18N
        jLabel4.setText("FIRST NAME");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, -1, -1));

        txtfname.setBackground(new java.awt.Color(232, 231, 232));
        txtfname.setFont(new java.awt.Font("Catamaran", 0, 12)); // NOI18N
        txtfname.setForeground(new java.awt.Color(126, 126, 126));
        txtfname.setText("Juan");
        txtfname.setToolTipText("Enter your first name");
        txtfname.setBorder(null);
        txtfname.setName(""); // NOI18N
        txtfname.setOpaque(false);
        txtfname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtfnameFocusGained(evt);
            }
        });
        txtfname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfnameActionPerformed(evt);
            }
        });
        getContentPane().add(txtfname, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 290, 20));

        txtlname.setBackground(new java.awt.Color(232, 231, 232));
        txtlname.setFont(new java.awt.Font("Catamaran", 0, 12)); // NOI18N
        txtlname.setForeground(new java.awt.Color(126, 126, 126));
        txtlname.setText("Dela Cruz");
        txtlname.setToolTipText("Enter your last name");
        txtlname.setBorder(null);
        txtlname.setOpaque(false);
        getContentPane().add(txtlname, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 290, 20));

        jLabel5.setFont(new java.awt.Font("Catamaran", 0, 12)); // NOI18N
        jLabel5.setText("LAST NAME");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, -1, -1));

        txtaddress.setBackground(new java.awt.Color(232, 231, 232));
        txtaddress.setFont(new java.awt.Font("Catamaran", 0, 12)); // NOI18N
        txtaddress.setForeground(new java.awt.Color(126, 126, 126));
        txtaddress.setText("ex. Batangas City");
        txtaddress.setToolTipText("Enter your home address");
        txtaddress.setBorder(null);
        txtaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaddressActionPerformed(evt);
            }
        });
        getContentPane().add(txtaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 290, 20));

        jLabel6.setFont(new java.awt.Font("Catamaran", 0, 12)); // NOI18N
        jLabel6.setText("ADDRESS");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, -1, -1));

        txttelno.setBackground(new java.awt.Color(232, 231, 232));
        txttelno.setFont(new java.awt.Font("Catamaran", 0, 12)); // NOI18N
        txttelno.setForeground(new java.awt.Color(126, 126, 126));
        txttelno.setText("9 digit number excluding 09");
        txttelno.setToolTipText("Enter your phone number");
        txttelno.setBorder(null);
        getContentPane().add(txttelno, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, 270, 20));

        jLabel7.setFont(new java.awt.Font("Catamaran", 0, 12)); // NOI18N
        jLabel7.setText("PHONE NO.");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, -1, -1));

        txtsalary.setBackground(new java.awt.Color(232, 231, 232));
        txtsalary.setFont(new java.awt.Font("Catamaran", 0, 12)); // NOI18N
        txtsalary.setForeground(new java.awt.Color(126, 126, 126));
        txtsalary.setText("ex. 9000");
        txtsalary.setToolTipText("Enter your Salary");
        txtsalary.setBorder(null);
        txtsalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsalaryActionPerformed(evt);
            }
        });
        getContentPane().add(txtsalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, 240, 20));

        jLabel8.setFont(new java.awt.Font("Catamaran", 0, 12)); // NOI18N
        jLabel8.setText("SALARY");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, -1, -1));

        txtdepart.setBackground(new java.awt.Color(232, 231, 232));
        txtdepart.setFont(new java.awt.Font("Catamaran", 0, 12)); // NOI18N
        txtdepart.setForeground(new java.awt.Color(126, 126, 126));
        txtdepart.setText("ex. HR Department");
        txtdepart.setToolTipText("Enter your department");
        txtdepart.setBorder(null);
        txtdepart.setOpaque(false);
        getContentPane().add(txtdepart, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 360, 280, 20));

        jLabel9.setFont(new java.awt.Font("Catamaran", 0, 12)); // NOI18N
        jLabel9.setText("DEPARTMENT");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, -1, -1));

        btnSubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btsubmit.png"))); // NOI18N
        btnSubmit.setBorder(null);
        btnSubmit.setContentAreaFilled(false);
        btnSubmit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSubmit.setOpaque(false);
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 430, -1, 40));

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnback.png"))); // NOI18N
        btnCancel.setBorder(null);
        btnCancel.setBorderPainted(false);
        btnCancel.setContentAreaFilled(false);
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancel.setOpaque(false);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 35));

        jLabel3.setFont(new java.awt.Font("Catamaran", 0, 12)); // NOI18N
        jLabel3.setText("+639");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, 41, -1));

        jLabel11.setFont(new java.awt.Font("HelvLight", 0, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(47, 47, 47));
        jLabel11.setText("Please fill your information below. ");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 142, 410, 0));

        jSeparator2.setBackground(new java.awt.Color(232, 231, 232));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 380, 10));

        jSeparator3.setBackground(new java.awt.Color(232, 231, 232));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 380, 10));

        jSeparator4.setBackground(new java.awt.Color(232, 231, 232));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, 380, 10));

        jSeparator5.setBackground(new java.awt.Color(232, 231, 232));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 380, 10));

        jLabel12.setFont(new java.awt.Font("Catamaran Light", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(5, 118, 209));
        jLabel12.setText("Privacy Conditions.");
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 400, 100, -1));

        jSeparator6.setBackground(new java.awt.Color(232, 231, 232));
        getContentPane().add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 380, 10));

        jSeparator7.setBackground(new java.awt.Color(232, 231, 232));
        getContentPane().add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, 380, 10));

        jLabel13.setFont(new java.awt.Font("Catamaran Light", 1, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(5, 118, 209));
        jLabel13.setText("Terms and Condition.");
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, 100, -1));

        jCheckBox1.setBackground(new java.awt.Color(232, 231, 232));
        jCheckBox1.setFont(new java.awt.Font("Catamaran Light", 0, 11)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(126, 126, 126));
        jCheckBox1.setText("I agree to the");
        jCheckBox1.setBorder(null);
        jCheckBox1.setBorderPaintedFlat(true);
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 400, 90, -1));

        jCheckBox2.setBackground(new java.awt.Color(232, 231, 232));
        jCheckBox2.setFont(new java.awt.Font("Catamaran Light", 0, 11)); // NOI18N
        jCheckBox2.setForeground(new java.awt.Color(126, 126, 126));
        jCheckBox2.setText("I agree to the");
        jCheckBox2.setBorder(null);
        jCheckBox2.setBorderPaintedFlat(true);
        getContentPane().add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 400, 90, -1));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Back");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 18, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main2form480.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtfnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfnameActionPerformed

    private void txtaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaddressActionPerformed

    private void txtsalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsalaryActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        String empno=txtno.getText();
        String empfname=txtfname.getText();
        String emplname=txtlname.getText();
        String address=txtaddress.getText();
        String telno=txttelno.getText();
        String salary=txtsalary.getText();
        String depart=txtdepart.getText();
        
        try {
            pst = con.prepareStatement("INSERT INTO employee(empno,fname,lname,address,telno,salary,department)VALUES(?,?,?,?,?,?,?)");
            pst.setString(1,empno);
            pst.setString(2,empfname);
            pst.setString(3,emplname);
            pst.setString(4,address);
            pst.setString(5,telno);
            pst.setString(6,salary);
            pst.setString(7,depart);  
            
            int k = pst.executeUpdate();
            
            if(k==1){
                JOptionPane.showMessageDialog(this, "Successfully Inserted!");
                AutoID();
               txtfname.setText(""); 
               txtlname.setText(""); 
               txtaddress.setText(""); 
               txttelno.setText(""); 
               txtsalary.setText(""); 
               txtdepart.setText(""); 
            }else{
               JOptionPane.showMessageDialog(this, "Error to insert!!");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Employee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        
        new MainForm().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtfnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfnameFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtfnameFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSubmit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtdepart;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtlname;
    private javax.swing.JLabel txtno;
    private javax.swing.JTextField txtsalary;
    private javax.swing.JTextField txttelno;
    // End of variables declaration//GEN-END:variables
}
